site_name: "DevOps Automation Labs"
site_description: "Central hub for DevOps automation demos, labs, and resources"
site_author: "DevOps Automation Labs"
repo_url: "https://github.com/DevOpsAutomationLabs/Index"
repo_name: "DevOpsAutomationLabs/Index"
edit_uri: edit/main/docs/

INHERIT: base.yml

nav:
  - Home: index.md
  - Tags: tags.md